GymAdministrationSys/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('pagedetail/<int:id>', views.page_detail, name='pagedetail'),
    path('faqs', views.faq_list, name='faq'),
    path('contact_us', views.contact_us, name='contact_us'),
    path('enquiry', views.enquiry, name='enquiry'),
    path('gallery', views.gallery, name='gallery'),
    path('gallerydetail/<int:id>', views.gallery_detail, name='gallery_detail'),
    path('pricing', views.pricing, name='pricing'),
    path('accounts/signup', views.signup, name='signup'),

    # Checkout & Pay for a plan
    path('checkout/<int:plan_id>', views.checkout, name='checkout'),
    path('pay_success', views.pay_success, name='pay_success'),
    path('pay_cancel', views.pay_cancel, name='pay_cancel'),

    # User Dashboard
    path('user_dashboard', views.user_dashboard, name='user_dashboard'),
    path('update_profile', views.update_profile, name='update_profile'),

    # Trainer Login, Dashboard, profile, Logout, assigned subscribers, payments
    path('trainerlogin', views.trainerlogin, name='trainerlogin'),
    path('trainerlogout', views.trainerlogout, name='trainerlogout'),
    path('trainer_dashboard', views.trainer_dashboard, name='trainer_dashboard'),
    path('trainer_profile', views.trainer_profile, name='trainer_profile'),
    path('trainer_payments', views.trainer_payments, name='trainer_payments'),
    path('trainer_subscribers', views.trainer_subscribers, name='trainer_subscribers'),
    path('trainer_change_password', views.trainer_change_password, name='trainer_change_password'),
    path('trainer_notifs', views.trainer_notifs, name='trainer_notifs'),
    path('mark_read_trainer_notif', views.mark_read_trainer_notif, name='mark_read_trainer_notif'),
    

    # Notifications
    path('notifs', views.notifs, name='notifs'),
    path('get_notifs', views.get_notifs, name='get_notifs'),
    path('mark_read_notif', views.mark_read_notif, name='mark_read_notif'),

    # Messages
    path('messages', views.trainer_msgs, name='messages'),

    # Reports
    path('report_for_user', views.report_for_user, name='report_for_user'),
    path('report_for_trainer', views.report_for_trainer, name='report_for_trainer'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User

# Send a notification after creating or saving an instance of any model to the custom function we make
# lie new user creation will send user info to the subscriber model
from django.db.models.signals import post_save
from django.dispatch import receiver

import json
import asyncio
from asgiref.sync import async_to_sync, sync_to_async
from channels.layers import get_channel_layer


# Website home page banner
class Banners(models.Model):
    img = models.ImageField(upload_to="banners/")
    alt_text = models.CharField(max_length=150)

    # Edit model name in Admin panel (by removing the extra s)
    class Meta:
        verbose_name_plural = "Banners"

    # Show the name of images in Banners section that will be named through the panel section (admin panel)
    def __str__(self):
        return self.alt_text
    
    def image_tag(self):
        # Returns an HTML <img> tag to display the product's image in the admin interface
        # The image is displayed as a thumbnail with a width of 80 pixels.
        return mark_safe("<img src='%s' width='80'/>" %(self.img.url))


# The offered services
class Service(models.Model):
    title = models.CharField(max_length=150)
    detail = models.TextField()
    img = models.ImageField(upload_to="services/", null=True)
    
    # Show alt text of images in Service section (admin panel)
    def __str__(self):
        return self.title
    
    def image_tag(self):
        return mark_safe("<img src='%s' width='80'/>" %(self.img.url))


# Pages
class Page(models.Model):
    title = models.CharField(max_length=150)
    detail = models.TextField()

    def __str__(self):
        return self.title
    

# FAQ
class faq(models.Model):
    question = models.TextField()
    answer = models.TextField()

    class Meta:
        verbose_name_plural = "FAQs"

    def __str__(self):
        return self.question


# Enquiry
class Enquiry(models.Model):
    full_name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    detail = models.TextField()
    send_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Enquiries"
    
    def __str__(self):
        return self.question


# Gallery (make a separate gallery for different occassion e.g. Competitions, Workout, Cardio outside etc...)

class Gallery(models.Model):
    title = models.CharField(max_length=150)
    detail = models.TextField()
    img = models.ImageField(upload_to="gallery/", null=True)

    class Meta:
        verbose_name_plural = "Galleries"
    
    # Show alt text of images in Service section (admin panel)
    def __str__(self):
        return self.title
    
    def image_tag(self):
        return mark_safe("<img src='%s' width='80'/>" %(self.img.url))
    

# Gallery Images (Add images to deifferent galleries)
class GalleryImage(models.Model):
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE, null=True)
    alt_text = models.CharField(max_length=150)
    img = models.ImageField(upload_to="gallery_images/", null=True)
    
    # Show alt text of images in Service section (admin panel)
    def __str__(self):
        return self.alt_text
    
    def image_tag(self):
        return mark_safe("<img src='%s' width='80'/>" %(self.img.url))


# Subscription plans (pricing)
class SubPlan(models.Model):
    title = models.CharField(max_length=150)
    price = models.IntegerField()

    # Set a maximum number for memebrs to sign up for the plan and disable the "get started" button when the plan reaches the max number
    max_member = models.IntegerField(null=True)
    highlight = models.BooleanField(default=False, null=True)

    #Set validation days for the subscription plan
    valid_days = models.IntegerField(null=True)

    # Plan title (basic, Advanced etc...)
    def __str__(self):
        return self.title
    

# Subscription plan features
class SubPlanFeature(models.Model):
    # Many to many, so each feature can be added to the applicable plan instead of adding manually inside the plan
    # We add the feature once in the admin panel and select the plan that could contain this feature
    subplan = models.ManyToManyField(SubPlan)
    feature = models.CharField(max_length=150)

    # Show plan title in the comparison table
    def __str__(self):
        return self.feature
    

# Plans discounts
class PlanDiscount(models.Model):
    subplan = models.ForeignKey(SubPlan, on_delete=models.CASCADE, null=True)
    total_months = models.IntegerField()
    total_discount = models.IntegerField()

    def __str__(self):
        return str(self.total_months)


# Subscriber
class Subscriber(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    mobile = models.CharField(max_length=15)
    address = models.TextField()
    img = models.ImageField(upload_to="subs/")

    def __str__(self):
        return str(self.user)

    def image_tag(self):
        if self.img:
            return mark_safe("<img src='%s' width='80'/>" %(self.img.url))
        else:
            return 'no-image'


# When creating a new user it will be added to the subscribers database
@receiver(post_save, sender=User)
def create_subscriber(sender, instance, created, **kwargs):
    if created:
        Subscriber.objects.create(user=instance)


# Subscription
class Subscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    plan = models.ForeignKey(SubPlan, on_delete=models.CASCADE, null=True)
    price = models.CharField(max_length=15)
    reg_date = models.DateField(auto_now_add=True, null=True)

    # Other data will be displayed from the admin panel 


# Trainers
class Trainer(models.Model):
    full_name = models.CharField(max_length=150)
    username = models.CharField(max_length=100, null=True)
    password = models.CharField(max_length=100, null=True)
    mobile = models.CharField(max_length=15)
    address = models.TextField()
    is_active = models.BooleanField(default=False)
    details = models.TextField()
    img = models.ImageField(upload_to="trainers/")
    salary = models.IntegerField(default=1)

    # Social Media links to trainer's profile
    facebook = models.CharField(max_length=500, null=True)
    instagram = models.CharField(max_length=500, null=True)
    twitter = models.CharField(max_length=500, null=True)
    youtube = models.CharField(max_length=500, null=True)
    blog = models.CharField(max_length=500, null=True)

    def __str__(self):
        return str(self.full_name)
    
    def image_tag(self):
        if self.img:
            return mark_safe("<img src='%s' width='80'/>" %(self.img.url))
        else:
            return 'no-image'


# Notifications (Json response via AJAX)
class Notify(models.Model):
    notify_detail = models.TextField()
    read_by_user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    read_by_trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        verbose_name_plural = "Notifications"

    def __str__(self):
        return str(self.notify_detail)
    

# Notifications - Mark as read by user
class NotifUserStatus(models.Model):
    notif = models.ForeignKey(Notify, on_delete=models.CASCADE, related_name='notifuserstatus')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Notification Status"


# Assign subscriber to a trainer
class AssignSubscriber(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user)


# Trainer's Achievements
class TrainerAcheivement(models.Model):
    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    date = models.DateField(null=True)
    img = models.ImageField(upload_to="trainers_achievments/")
    details = models.TextField()

    def __str__(self):
        return str(self.title)
    
    def image_tag(self):
        if self.img:
            return mark_safe("<img src='%s' width='80'/>" %(self.img.url))
        else:
            return 'no-image'
        

# Trainer's Salary
class TrainerSalary(models.Model):
    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE)
    amount = models.IntegerField()
    amount_date = models.DateField()
    remarks = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = "Trainers' Salaries"

    def __str__(self):
        return str(self.trainer.full_name)
    

# Training Notifications
class TrainerNotification(models.Model):
    notif_msg = models.TextField()

    def __str__(self):
        return str(self.notif_msg)


    def save(self,  *args, **kwargs):
        super(TrainerNotification, self).save(*args, **kwargs)
        channel_layer = get_channel_layer()
        notif = self.notif_msg
        total = TrainerNotification.objects.all().count()
        async_to_sync(channel_layer.group_send) (
            'noti_group_name', {
                'type' : 'send_notificatio',
                'value' : json.dumps({'notif':notif, 'total': total})}
            )



# Notifications - Mark as read by trainer
class NotifTrainerStatus(models.Model):
    notif = models.ForeignKey(TrainerNotification, on_delete=models.CASCADE, related_name='trainernotification')
    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE, related_name='trainer')
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Trainer Notification Status"


# Subscribers and Admin Messages to Trainer
class TrainerMessage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from . import models

# Enquiry form
class EnquiryForm(forms.ModelForm):
    class Meta:
        model = models.Enquiry
        fields = ("full_name", "email", "detail",)


# User registration form with the below fields
class SignUp(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password1', 'password2')


# Edit user's profile
class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username')


# Django session for trainers login
class TrainerLoginForm(forms.ModelForm):
    class Meta:
        model = models.Trainer
        fields = ('username', 'password')


# Trainer Profile Form
class TrainerProfileForm(forms.ModelForm):
    class Meta:
        model = models.Trainer
        fields = ('full_name', 'mobile', 'address', 'img', 'details', 'facebook', 'instagram', 'twitter', 'youtube', 'blog')


# Trainer - Change Password
class TrainerChangePasswordForm(forms.Form):
    new_password = forms.CharField(max_length=50, required=True)


# Reports: Send reports from trainer to user and vice versa
class ReportForTrainerForm(forms.ModelForm):
    class Meta:
        model = models.TrainerSubscriberReport
        fields = ('report_for_trainer', 'report_msg')

class ReportForUserForm(forms.ModelForm):
    class Meta:
        model = models.TrainerSubscriberReport
        fields = ('report_for_user', 'report_msg', 'report_from_trainer')
        widgets = {'report_from_trainer': forms.HiddenInput()}


class ReportForTrainerForm(forms.ModelForm):
    class Meta:
        model = models.TrainerSubscriberReport
        fields = ('report_for_trainer', 'report_msg', 'report_from_user')
        widgets = {'report_from_user': forms.HiddenInput()}

main/templates/user/dashboard.html
{% extends "base.html" %} {% load static %} {% block content %}

<!-- Main Start -->
<main>
  <head>
    <title>GymSync - User Dashboard</title>
  </head>

  <section class="container my-4">
    <div class="row">
      <div class="col-3">
        {% include 'user/left_sidebar.html' %}</div>
      <div class="col-9">
        <h3 class="mb-4 border-bottom pb-1">Dashboard</h3>
        <!-- Show User's Current plan, price, and assigned trainer-->
        <div class="row">
          <div class="col-md-4">
            <div class="card">
              <h5 class="card-header">Current Package</h5>
              <div class="card-body">
                <h6 class="card-text text-success">{{current_plan.plan}}</h6>
                <p>Price: EGP{{current_plan.price}}</p>
                <p>Subscribed on {{current_plan.reg_date}}</p>
                <p>Valid till {{end_date}}</p>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="card">
              <!-- The assigned Triner profile, image and social media links-->
              <h5 class="card-header">Assigned Trainer</h5>

              <div class="card-body">
                <h6 class="card-text margin:15px">
                  Coach: {{my_trainer.trainer.full_name}}
                  <img
                    src="{{my_trainer.trainer.img.url}}"
                    class="rounded float-right img-thumbnail"
                    alt="{{my_trainer.trainer.full_name}} "
                  />
                </h6>
              </div>
              <div class="card-footer">
                <a href="{{my_trainer.trainer.facebook}}" title="Facebook">
                  <i class="fa fa-facebook"></i
                ></a>
                <a href="{{my_trainer.trainer.instagram}}" title="Instagram">
                  <i class="fa fa-instagram"></i
                ></a>
                <a href="{{my_trainer.trainer.twitter}}" title="Twitter">
                  <i class="fa fa-twitter"></i
                ></a>
                <a href="{{my_trainer.trainer.youtube}}" title="Youtube">
                  <i class="fa fa-youtube"></i
                ></a>
                <a href="{{my_trainer.trainer.blog}}" title="Blog">
                  <i class="fa fa-blogger-b"></i>B</a
                >

                <!-- Trainer's achievments-->
                <button
                  data-toggle="modal"
                  data-target="#AchievmentModal"
                  title="Achievments"
                  class="float-end btn btn-sm btn-success"
                >
                  <i class="fa fa-trophy"></i>
                </button>
                <!-- Modal -->
                <div
                  class="modal fade"
                  id="AchievmentModal"
                  tabindex="-1"
                  role="dialog"
                  aria-labelledby="exampleModalLabel"
                  aria-hidden="true"
                >
                  <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">
                          {{my_trainer.trainer.full_name}}'s Achievments
                        </h5>
                        <button
                          type="button"
                          class="close"
                          data-dismiss="modal"
                          aria-label="Close"
                        >
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        <table class="table table-hover">
                          <thead>
                            <tr>
                              <th>Title</th>
                              <th>Image</th>
                              <th>Date</th>
                              <th>Details</th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for acheivement in my_trainer.trainer.traineracheivement_set.all %}
                            <tr>
                              <th>{{acheivement.title}}</th>
                              <th>
                                <img src="{{acheivement.img.url}}" width="80" />
                              </th>
                              <th>{{acheivement.detail}}</th>
                            </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End -->
</main>
{% endblock %}

main/templates/user/left_sidebar.html
<div class="list-group">
  <a
    href="{% url 'user_dashboard' %}"
    class="list-group-item {%if request.path == '/user_dashboard'%} active {% endif %}"
    >Dashboard</a
  >
  <a
    href="{% url 'update_profile' %}"
    class="list-group-item {%if request.path == '/update_profile'%} active {% endif %}"
    >Profile</a
  >
  <a
    href="{% url 'password_change' %}"
    class="list-group-item {% if request.path == '/accounts/password_change/' %} active {% endif %}"
    >Change Password</a
  >
  <a
    href="{% url 'notifs' %}"
    class="list-group-item {%if request.path == '/notifs'%} active {% endif %}"
    >Notifications <span class="float-end badge bg-info mt-1">{{totalUnread}}</span></a
  >
  <a href="#" class="list-group-item">Messages <span class="float-end badge bg-info mt-1 {%if request.path == '/#'%} active {% endif %}">{{totalUnread}}</span></a>
  
  <a href="{% url 'report_for_trainer' %}" class="list-group-item {%if request.path == '/report_for_trainer'%} active {% endif %}">Report To A Trainer</a>
</div>

main/templates/user/password_change_done.html
{% extends "base.html" %} {% block content %}

<!-- Main Start -->
<main class="container my-4">
  <head>
    <title>GymSync - User Dashboard/Change Password</title>
  </head>

  <div class="row">
    <div class="col-3">{% include 'user/left_sidebar.html' %}</div>
    <div class="col-9">
      <h3 class="mb-4 border-bottom pb-1">
        Password has been changed Successfuly
      </h3>
    </div>
  </div>

  <!-- End -->
</main>
{% endblock %}

main/templates/user/password_change_form.html
{% extends "base.html" %} {% block content %}

<!-- Main Start -->
<main>
  <head>
    <title>GymSync - User Dashboard/Change Password</title>
  </head>

  <section class="container my-4">
    <h3 class="mb-4 border-bottom pb-1">Change Password</h3>
    <div class="row">
      <div class="col-3">{% include 'user/left_sidebar.html' %}</div>

      <div class="col-9">
        <table class="table table-bordered">
          <form method="post">
            {% csrf_token %} {{ form.as_table }}
            <tr>
              <td colspan="2">
                <input type="submit" value="save" class="btn btn-primary" />
              </td>
            </tr>
          </form>
        </table>
      </div>
    </div>
  </section>
  <!-- End -->
</main>
{% endblock %}

main/templates/user/update_profile.html
{% extends "base.html" %} {% block content %}

<!-- Main Start -->
<main>
  <head>
    <title>GymSync - User Dashboard/Edit Profile</title>
  </head>

  <section class="container my-4">
    <div class="row">
      <div class="col-3">{% include 'user/left_sidebar.html' %}</div>
      <div class="col-9">
        <h3 class="mb-4 border-bottom pb-1">Edit your profile</h3>
        {% if msg %}
        <p class="text-success">{{msg}}</p>
        {% endif %}
        <form method="post" action="">
          <table class="table table-bordered">
            {% csrf_token %} {{ form.as_table }}
            <tr>
              <td colspan="2">
                <input type="submit" clas="btn btn-primary" />
              </td>
            </tr>
          </table>
        </form>
      </div>
    </div>
  </section>
  <!-- End -->
</main>
{% endblock %}