GymAdministrationSys/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('pagedetail/<int:id>', views.page_detail, name='pagedetail'),
    path('faqs', views.faq_list, name='faq'),
    path('contact_us', views.contact_us, name='contact_us'),
    path('enquiry', views.enquiry, name='enquiry'),
    path('gallery', views.gallery, name='gallery'),
    path('gallerydetail/<int:id>', views.gallery_detail, name='gallery_detail'),
    path('pricing', views.pricing, name='pricing'),
    path('accounts/signup', views.signup, name='signup'),

    # Checkout & Pay for a plan
    path('checkout/<int:plan_id>', views.checkout, name='checkout'),
    path('pay_success', views.pay_success, name='pay_success'),
    path('pay_cancel', views.pay_cancel, name='pay_cancel'),

    # User Dashboard
    path('user_dashboard', views.user_dashboard, name='user_dashboard'),
    path('update_profile', views.update_profile, name='update_profile'),

    # Trainer Login, Dashboard, profile, Logout, assigned subscribers, payments
    path('trainerlogin', views.trainerlogin, name='trainerlogin'),
    path('trainerlogout', views.trainerlogout, name='trainerlogout'),
    path('trainer_dashboard', views.trainer_dashboard, name='trainer_dashboard'),
    path('trainer_profile', views.trainer_profile, name='trainer_profile'),
    path('trainer_payments', views.trainer_payments, name='trainer_payments'),
    path('trainer_subscribers', views.trainer_subscribers, name='trainer_subscribers'),
    path('trainer_change_password', views.trainer_change_password, name='trainer_change_password'),
    path('trainer_notifs', views.trainer_notifs, name='trainer_notifs'),
    path('mark_read_trainer_notif', views.mark_read_trainer_notif, name='mark_read_trainer_notif'),
    

    # Notifications
    path('notifs', views.notifs, name='notifs'),
    path('get_notifs', views.get_notifs, name='get_notifs'),
    path('mark_read_notif', views.mark_read_notif, name='mark_read_notif'),

    # Messages
    path('messages', views.trainer_msgs, name='messages'),

    # Reports
    path('report_for_user', views.report_for_user, name='report_for_user'),
    path('report_for_trainer', views.report_for_trainer, name='report_for_trainer'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User

# Send a notification after creating or saving an instance of any model to the custom function we make
# lie new user creation will send user info to the subscriber model
from django.db.models.signals import post_save
from django.dispatch import receiver

import json
import asyncio
from asgiref.sync import async_to_sync, sync_to_async
from channels.layers import get_channel_layer


# Website home page banner
class Banners(models.Model):
    img = models.ImageField(upload_to="banners/")
    alt_text = models.CharField(max_length=150)

    # Edit model name in Admin panel (by removing the extra s)
    class Meta:
        verbose_name_plural = "Banners"

    # Show the name of images in Banners section that will be named through the panel section (admin panel)
    def __str__(self):
        return self.alt_text
    
    def image_tag(self):
        # Returns an HTML <img> tag to display the product's image in the admin interface
        # The image is displayed as a thumbnail with a width of 80 pixels.
        return mark_safe("<img src='%s' width='80'/>" %(self.img.url))


# The offered services
class Service(models.Model):
    title = models.CharField(max_length=150)
    detail = models.TextField()
    img = models.ImageField(upload_to="services/", null=True)
    
    # Show alt text of images in Service section (admin panel)
    def __str__(self):
        return self.title
    
    def image_tag(self):
        return mark_safe("<img src='%s' width='80'/>" %(self.img.url))


# Pages
class Page(models.Model):
    title = models.CharField(max_length=150)
    detail = models.TextField()

    def __str__(self):
        return self.title
    

# FAQ
class faq(models.Model):
    question = models.TextField()
    answer = models.TextField()

    class Meta:
        verbose_name_plural = "FAQs"

    def __str__(self):
        return self.question


# Enquiry
class Enquiry(models.Model):
    full_name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    detail = models.TextField()
    send_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Enquiries"
    
    def __str__(self):
        return self.question


# Gallery (make a separate gallery for different occassion e.g. Competitions, Workout, Cardio outside etc...)

class Gallery(models.Model):
    title = models.CharField(max_length=150)
    detail = models.TextField()
    img = models.ImageField(upload_to="gallery/", null=True)

    class Meta:
        verbose_name_plural = "Galleries"
    
    # Show alt text of images in Service section (admin panel)
    def __str__(self):
        return self.title
    
    def image_tag(self):
        return mark_safe("<img src='%s' width='80'/>" %(self.img.url))
    

# Gallery Images (Add images to deifferent galleries)
class GalleryImage(models.Model):
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE, null=True)
    alt_text = models.CharField(max_length=150)
    img = models.ImageField(upload_to="gallery_images/", null=True)
    
    # Show alt text of images in Service section (admin panel)
    def __str__(self):
        return self.alt_text
    
    def image_tag(self):
        return mark_safe("<img src='%s' width='80'/>" %(self.img.url))


# Subscription plans (pricing)
class SubPlan(models.Model):
    title = models.CharField(max_length=150)
    price = models.IntegerField()

    # Set a maximum number for memebrs to sign up for the plan and disable the "get started" button when the plan reaches the max number
    max_member = models.IntegerField(null=True)
    highlight = models.BooleanField(default=False, null=True)

    #Set validation days for the subscription plan
    valid_days = models.IntegerField(null=True)

    # Plan title (basic, Advanced etc...)
    def __str__(self):
        return self.title
    

# Subscription plan features
class SubPlanFeature(models.Model):
    # Many to many, so each feature can be added to the applicable plan instead of adding manually inside the plan
    # We add the feature once in the admin panel and select the plan that could contain this feature
    subplan = models.ManyToManyField(SubPlan)
    feature = models.CharField(max_length=150)

    # Show plan title in the comparison table
    def __str__(self):
        return self.feature
    

# Plans discounts
class PlanDiscount(models.Model):
    subplan = models.ForeignKey(SubPlan, on_delete=models.CASCADE, null=True)
    total_months = models.IntegerField()
    total_discount = models.IntegerField()

    def __str__(self):
        return str(self.total_months)


# Subscriber
class Subscriber(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    mobile = models.CharField(max_length=15)
    address = models.TextField()
    img = models.ImageField(upload_to="subs/")

    def __str__(self):
        return str(self.user)

    def image_tag(self):
        if self.img:
            return mark_safe("<img src='%s' width='80'/>" %(self.img.url))
        else:
            return 'no-image'


# When creating a new user it will be added to the subscribers database
@receiver(post_save, sender=User)
def create_subscriber(sender, instance, created, **kwargs):
    if created:
        Subscriber.objects.create(user=instance)


# Subscription
class Subscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    plan = models.ForeignKey(SubPlan, on_delete=models.CASCADE, null=True)
    price = models.CharField(max_length=15)
    reg_date = models.DateField(auto_now_add=True, null=True)

    # Other data will be displayed from the admin panel 


# Trainers
class Trainer(models.Model):
    full_name = models.CharField(max_length=150)
    username = models.CharField(max_length=100, null=True)
    password = models.CharField(max_length=100, null=True)
    mobile = models.CharField(max_length=15)
    address = models.TextField()
    is_active = models.BooleanField(default=False)
    details = models.TextField()
    img = models.ImageField(upload_to="trainers/")
    salary = models.IntegerField(default=1)

    # Social Media links to trainer's profile
    facebook = models.CharField(max_length=500, null=True)
    instagram = models.CharField(max_length=500, null=True)
    twitter = models.CharField(max_length=500, null=True)
    youtube = models.CharField(max_length=500, null=True)
    blog = models.CharField(max_length=500, null=True)

    def __str__(self):
        return str(self.full_name)
    
    def image_tag(self):
        if self.img:
            return mark_safe("<img src='%s' width='80'/>" %(self.img.url))
        else:
            return 'no-image'


# Notifications (Json response via AJAX)
class Notify(models.Model):
    notify_detail = models.TextField()
    read_by_user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    read_by_trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        verbose_name_plural = "Notifications"

    def __str__(self):
        return str(self.notify_detail)
    

# Notifications - Mark as read by user
class NotifUserStatus(models.Model):
    notif = models.ForeignKey(Notify, on_delete=models.CASCADE, related_name='notifuserstatus')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Notification Status"


# Assign subscriber to a trainer
class AssignSubscriber(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user)


# Trainer's Achievements
class TrainerAcheivement(models.Model):
    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    date = models.DateField(null=True)
    img = models.ImageField(upload_to="trainers_achievments/")
    details = models.TextField()

    def __str__(self):
        return str(self.title)
    
    def image_tag(self):
        if self.img:
            return mark_safe("<img src='%s' width='80'/>" %(self.img.url))
        else:
            return 'no-image'
        

# Trainer's Salary
class TrainerSalary(models.Model):
    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE)
    amount = models.IntegerField()
    amount_date = models.DateField()
    remarks = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = "Trainers' Salaries"

    def __str__(self):
        return str(self.trainer.full_name)
    

# Training Notifications
class TrainerNotification(models.Model):
    notif_msg = models.TextField()

    def __str__(self):
        return str(self.notif_msg)


    def save(self,  *args, **kwargs):
        super(TrainerNotification, self).save(*args, **kwargs)
        channel_layer = get_channel_layer()
        notif = self.notif_msg
        total = TrainerNotification.objects.all().count()
        async_to_sync(channel_layer.group_send) (
            'noti_group_name', {
                'type' : 'send_notificatio',
                'value' : json.dumps({'notif':notif, 'total': total})}
            )



# Notifications - Mark as read by trainer
class NotifTrainerStatus(models.Model):
    notif = models.ForeignKey(TrainerNotification, on_delete=models.CASCADE, related_name='trainernotification')
    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE, related_name='trainer')
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Trainer Notification Status"


# Subscribers and Admin Messages to Trainer
class TrainerMessage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from . import models

# Enquiry form
class EnquiryForm(forms.ModelForm):
    class Meta:
        model = models.Enquiry
        fields = ("full_name", "email", "detail",)


# User registration form with the below fields
class SignUp(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password1', 'password2')


# Edit user's profile
class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username')


# Django session for trainers login
class TrainerLoginForm(forms.ModelForm):
    class Meta:
        model = models.Trainer
        fields = ('username', 'password')


# Trainer Profile Form
class TrainerProfileForm(forms.ModelForm):
    class Meta:
        model = models.Trainer
        fields = ('full_name', 'mobile', 'address', 'img', 'details', 'facebook', 'instagram', 'twitter', 'youtube', 'blog')


# Trainer - Change Password
class TrainerChangePasswordForm(forms.Form):
    new_password = forms.CharField(max_length=50, required=True)


# Reports: Send reports from trainer to user and vice versa
class ReportForTrainerForm(forms.ModelForm):
    class Meta:
        model = models.TrainerSubscriberReport
        fields = ('report_for_trainer', 'report_msg')

class ReportForUserForm(forms.ModelForm):
    class Meta:
        model = models.TrainerSubscriberReport
        fields = ('report_for_user', 'report_msg', 'report_from_trainer')
        widgets = {'report_from_trainer': forms.HiddenInput()}


class ReportForTrainerForm(forms.ModelForm):
    class Meta:
        model = models.TrainerSubscriberReport
        fields = ('report_for_trainer', 'report_msg', 'report_from_user')
        widgets = {'report_from_user': forms.HiddenInput()}

main/templates/base.html
<!DOCTYPE html>

{% load static %}
{% load bootstrap_icons %}
<html lang="en">

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Bootstrap CSS -->
    <link href={% static 'bootstrap.min.css' %} rel="stylesheet" />
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href={% static 'bootstrap-icons/font/boostrap-icons.css' %} />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    
    <!-- JQuery -->
    <script type="text/javascript" src={% static "jquery-3.7.1.min.js" %}></script>

    <!-- Bootstrap Popper - for Modal to pop-up-->
    <script type="text/javascript" src="{% static "popper.min.js" %}"></script>
    
    
    <!-- Website icon-->
    <link
      rel="icon"
      type="image/x-icon"
      href={% static "images/favicon.ico" %}
    />
  </head>

  <body>
    <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
      <div class="container">
        <!-- GymSync could be replaced with the logo that will be added through the admin oanel-->
        <a class="navbar-brand" href="{% url 'home' %}" style="color: #ffffff",>GymSync</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'home' %}" style="color: #ffffff">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url "gallery" %}" style="color: #ffffff"
                >Gallery</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "pricing" %}" style="color: #ffffff">Pricing</a>
            </li>
            <li class="nav-item">
              <a
                class="nav-link btn btn-sm btn-dark text-white"
                href="{% url "enquiry" %}"
                >Enquiry</a
              >
            </li>
            <li class="nav-item dropdown">
              <button
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarScrollingDropdown"
                role="button"
                data-bs-toggle="collapse"
                aria-expanded="false"
                style="color: #ffffff"
              >
                My Account
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
              <!-- If user is logged in then they won't see the login options otherwise they will see login options only -->
              {% if not request.user.is.authenticated %}
                {% if request.session.trainerlogin %}
                <li><a class="dropdown-item" href="{% url 'trainer_dashboard' %}">Dashboard</a></li>
                <li><a class="dropdown-item" href="{% url 'trainerlogout' %}">Logout</a></li>
                {% else %}
                <li><a class="dropdown-item" href="{% url 'trainerlogin' %}">Trainer Login</a></li>
                <li><a class="dropdown-item" href="{% url 'signup' %}">Sign Up</a></li>
                <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
                {% endif %}
              {% else %}
              <li><a class="dropdown-item" href="{% url 'user_dashboard' %}">Dashboard</a></li>
              <li><a class="dropdown-item" href="{% url 'update_profile' %}">Profile</a></li>
              <li><a class="dropdown-item" href="#">Settings</a></li>
              <li><a class="dropdown-item" href="{% url 'logout'%}">Logout</a></li>
              {% endif %}                
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- Header End -->
    {% block content %}
    {% endblock %}
    <!-- Footer Starts -->

    <footer class="container py-5">
      <p class="float-end"><a href="#">Back to top</a></p>
      <p>
        © 2024 GymSync, Inc.
        <!-- Show the details added in the detail section in the admin panel for each page based on the id-->
        <a href="{% url 'pagedetail' 2 %}">Privacy</a> .
        <a href="{% url 'pagedetail' 3 %}">Terms</a> .
        <a href="{% url 'faq' %}">F.A.Q.</a> .
        <a href="{% url 'contact_us' %}">Contact Us </a>
      </p>
    </footer>

    <!-- Bootstrap Bundle -->
    <script type="text/javascript" src={% static "bundle.min.js" %}></script>
  </body>
</html>

main/templates/cancel.html
{% extends "base.html" %} {% block content %}
<!-- Main Start -->
<main>
  <head>
    <title>GymSync - Payment is Cancelled</title>
  </head>
  <section class="container my-4">
    <h3>Payment is Cancelled</h3>
  </section>
  <!-- End -->
</main>
{% endblock %}

main/templates/contact_us.html
{% extends "base.html" %} {% block content %}
<!-- Main Start -->
<main>
  <head>
    <title>GymSync - Contact Us</title>
  </head>

  <section class="container my-4">
    <h1 class="text-center mb-4 section-heading border-bottom pb-2">Contact Us</h1>
    <div class="row">
        <div class="col-md-7">
            <ul>
                <h3>Faculty of Graduate Studies and Statistical Research</h3>
            </ul>
            <ul>
                <h4> Project Supervisor: Dr. Mustafa Ezzat </h4>
                </ul>

            <ul> 
                <h5>Team Members</h5>
                <h6>
                <li>Abdelrahman</li>
                <li>Kyrillos</li>
                <li>Mohamed</li>
                <li>Nagy</li>
                <li>Omar</li> 
                </h6>
            </ul>
            <ul>
                <h6 class="row align-content-end">Address: 5 Ahmed Zewail, Ad Doqi, Dokki, Giza Governorate 3750210</h6>
            </ul>
        </div>
        
        <div class="col-md-5">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3454.19526499789!2d31.20796117627849!3d30.03125541919422!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14584781682635a3%3A0x8e276197b00990b8!2sGraduate%20School%20of%20Statistical%20Research!5e0!3m2!1sen!2seg!4v1726917999891!5m2!1sen!2seg" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>

    </div>
  </section>
  <!-- End -->
</main>
{% endblock %}

main/templates/enquiry.html
{% extends "base.html" %} {% block content %} {% load static %}
<!-- Main Start -->
<main>
  <head>
    <title>GymSync - Enquiry</title>
  </head>

  <!-- Enquiry form if users are facing issues or having a question -->
  <section class="container my-4">
    <h1 class="text-center mb-4 section-heading border-bottom pb-2">
      Enquiry Form
    </h1>
    <div class="row">
      <div class="col-md-6">
        <img src={% static "images/enquiry.png" %} class="img-fluid" />
      </div>
      <div class="col-md-6">
        <!-- Show a message after the user submit an enquiry-->
        {% if msg %}
        <p class="text-success">{{msg}}</p>
        {% endif %}

        <!-- save the posted enquiry with csrf_token-->
        <form method="post" action="{% url 'enquiry' %}">
          {% csrf_token %}
          <table class="table table-bordered">
            {{form.as_table}}
            <tr>
              <td colspan="2">
                <input type="submit" class="btn btn-primary" />
              </td>
            </tr>
          </table>
        </form>
      </div>
    </div>
  </section>
  <!-- End -->
</main>
<!-- End -->
{% endblock%}

main/templates/faq.html
{% extends "base.html" %} {% block content %}
<!-- Main Start -->
<main>
  <head>
    <title>GymSync - F.A.Q.</title>
  </head>

  <section class="container my-4">
    <h1 class="text-center mb-4 section-heading border-bottom pb-2">F.A.Q.</h1>
    <div class="accordion" id="accordionExample">
      {% for faq in faqs %}
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
          <button
            class="accordion-button"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#collapseOne{{forloop.counter}}"
            aria-expanded="true"
            aria-controls="collapseOne"
          >
            <!-- Passing the questions added from the admin panel-->
            {{faq.question}}
          </button>
        </h2>
        <div
          id="collapseOne{{forloop.counter}}"
          class="accordion-collapse collapse"
          aria-labelledby="headingOne"
          data-bs-parent="#accordionExample"
        >
          <div class="accordion-body">
            <!-- Passing the answers added from the admin panel-->
            {{faq.answer}}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </section>
  <!-- End -->
</main>
{% endblock %}

main/templates/gallery.html
{% extends "base.html" %} {% block content %}
<!-- Main Start -->
<main>

  <head>
    <title>GymSync - Gallery</title>
  </head>

 
  <section class="container my-4">
    <h1 class="text-center mb-4 section-heading border-bottom pb-2">Gallery</h1>
    <div class="row">
      {% for gallery in gallerys %}
      <div class="col-md-4 mb-4">
        <div class="card">
          <img src="{{gallery.img.url}}" class="card-img-top" alt="{{gallery.title}}" />
          <div class="card-body">
            <h5 class="card-title">{{gallery.title}}</h5>
            <p class="card-text">{{gallery.detail}}</p>
            <a href="{% url "gallery_detail" gallery.id %}" class="btn btn-primary">View All</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </section>
  <!-- End -->
</main>
<!-- End -->

{% endblock %}

main/templates/gallery_images.html
{% extends "base.html" %} {% block content %}
<!-- Main Start -->
<main>
  <!-- Services -->
  <section class="container my-4">
    <h1 class="text-center mb-4 section-heading border-bottom pb-2">
      {{gallery.title}} Images
    </h1>
    <div class="row">
      {% for image in gallery_images %}
      <div class="col-md-4 mb-4">
        <div class="card">
          <img
            src="{{gimage.img.url}}"
            class="card-img-top"
            alt="{{gimage.alt_text}}"
          />
        </div>
      </div>
      {% endfor %}
    </div>
  </section>
  <!-- End -->
</main>
<!-- End -->

{% endblock %}

main/templates/order.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Order Email</title>
    </head>

    <body>
        <h3>{{title}}</h3>
</html>

main/templates/pricing.html
{% extends "base.html" %} 
{% block content %}
{% load check_package %}
{% load mathfilters %}
{% load static %}
<main>
  
  <head>
    <title>GymSync - Plans & Pricing</title>
  </head>

<!-- Bootstrap Icons -->
<link rel="stylesheet" type="text/css" href={% static 'bootstrap-icons/font/boostrap-icons.css' %} />

<!-- Main Start -->
<section class="container my-4">
  <h1 class="text-center mb-4 section-heading border-bottom pb-2">Plans</h1>
  <main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
      {% for plan in plans %}
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
          {% if plan.highlight %}
          <div class="card-header py-3 text-white bg-primary border-primary">
            {% else %}
            <div class="card-header py-3">
              {% endif %}
            <h4 class="my-0 fw-normal">{{plan.title}}</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">
              EGP {{plan.price}}<small class="text-muted fw-light">/{{plan.valid_days}} Days</small>
            </h1>
            <p class="text-success">Available Memberships {{plan.max_member | sub:plan.total_members}}</p>
            <ul class="list-unstyled mt-3 mb-4">
              {% for feature in plan.subplanfeature_set.all %}
              <li>{{feature.feature}}</li>
              {% endfor %}
            </ul>

            
            {% if request.user.is.authenticated %}

            <!-- Check on the subscribed package, and show already purchased under the plan which user has signed up for -->
            {% check_user_package request.user.id plan.id as check_pckg %}
            <!-- Check the valid days left in the subscription for the subscribed plan -->
            {% check_pckg_validity request.user.id plan.id as check_validity %}
              
              {% if check_pckg %}
                {% if check_validity %}
                    <!-- Instead of showing expired, will show get started so the user can subscribe again-->
                    <a href="{% url 'login' %}" type="button" class="w-100 btn btn-lg btn-outline-primary" >Get started</a>
                  {% else %}
                    <a href="#" class="w-100 btn btn-lg btn-dark disabled">Purchased</a>
                  {% endif %}
              {% else %}
                <a href="{% url 'checkout' plan.id %}" type="button" class="w-100 btn btn-lg btn-outline-primary">Get started</a>
              {% endif %}

            {% else %}
              <a href="{% url 'login' %}" type="button" class="w-100 btn btn-lg btn-outline-primary" >Get started</a>
            {% endif %}
          </div>
        </div>
      </div>
      
      {% endfor %}
    </div>

    <h2 class="display-6 text-center mb-4">Compare plans</h2>

    <div class="table-responsive">
      <table class="table text-center">
        <thead>
          <tr>
            <th style="width: 34%"></th>
            <!-- Show plan title in comparison header -->
            {% for plan in plans %}
            <th style="width: 22%">{{plan.title}}</th>
            {% endfor %}
          </tr>
        </thead>
        <tbody>
          <!-- Plans' Comparison Table-->
           {% for feature in features %}
          <tr>
            <th scope="row" class="text-start">{{feature.feature}}</th>
            {% for plan in plans %}
            <td>
              <!-- Show a check in front of the feature and below the plan that contains this feature and X if not -->
              {% if plan in feature.subplan.all %}
              <i class="bi bi-check-lg text-success"></i>
              {% else %}
              <i class="bi bi-x-lg text-danger"></i>
              {% endif %}              
            </td>
            {% endfor %}
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </main>
</section>
</main>
<!-- End -->
{% endblock %}